import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "Next 練習ページ（ログイン済み）",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				{children}
			</body>
		</html>
	);
}
